[package]
name = "solana_tournament"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.7.10"
spl-token = "3.2.0"
solana-sdk = "1.7.10"
solana-program-test = "1.7.10"

